name: Node.js CI  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    strategy:  
      matrix:  
        node-version: [14.x, 16.x]  
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Use Node.js ${{ matrix.node-version }}  
      uses: actions/setup-node@v2  
      with:  
        node-version: ${{ matrix.node-version }}  
    - name: Install pnpm  
      run: npm install pnpm -g  
    - name: Install dependencies  
      run: pnpm install  
    - name: Run dev server (optional, for testing)  
      run: pnpm dev  
    - name: Build project  
      run: pnpm build  
  
    # 如果需要部署到某个服务，可以在这里添加部署步骤  
    # 例如，使用GitHub Pages或FTP部署等  
    # - name: Deploy  
    #   uses: some-deployment-action@vX  
    #   with:  
    #     branch: "main"  
    #     folder: "path/to/build/output"  
    #     # 其他必要的配置...
